services:
  keuanganku-fe:
    build:
      context: .
      args:
        # Gunakan subdomain pamjaya.keuanganku.id
        - NEXT_PUBLIC_API_URL=https://pamjaya.keuanganku.id/api
    container_name: pamjaya-fe
    restart: always
    
    # Menambahkan environment PORT agar Next.js berjalan di 4002 di dalam container
    environment:
      - PORT=4002
      - NODE_ENV=production

    # Port Mapping terbaru dari Anda
    ports:
      - "3002:4002"

    networks:
      - e-daily-report-net

    # Resource Management
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

networks:
  e-daily-report-net:
    external: true
    name: e-daily-report_default
